/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inspect Image
         * @description Periksa satu gambar produk dan kembalikan keputusannya.
         *
         *     Pemeriksaan berlapis dua, dan itu disengaja. Lapisan di sini menolak
         *     kiriman yang jelas keliru sebelum menyentuh model - tipe MIME salah, berkas
         *     kosong, ukuran berlebih - sehingga pengguna mendapat pesan yang menjelaskan
         *     persoalannya. Lapisan kedua ada di dalam modul AI, yang memeriksa isi
         *     berkasnya sendiri; header `Content-Type` dikirim oleh klien dan tidak dapat
         *     dipercaya sebagai bukti bahwa isinya benar-benar gambar.
         */
        post: operations["inspect_image_api_v1_inspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Samples
         * @description Gambar contoh yang disediakan supaya sistem dapat dicoba tanpa unggahan.
         */
        get: operations["get_samples_api_v1_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model Info
         * @description Keterangan model yang sedang dilayani, dibaca dari pipeline yang hidup.
         */
        get: operations["get_model_info_api_v1_model_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Kesiapan layanan beserta lapisan mana yang aktif.
         *
         *     `status` menjadi `degraded`, bukan `ok`, ketika model deteksi tidak
         *     tersedia. Melaporkan `ok` pada layanan yang tidak dapat memeriksa apa pun
         *     akan menyembunyikan kegagalan dari siapa pun yang memantau.
         */
        get: operations["health_check_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnomalyResult
         * @description Skor anomali beserta ambang yang dipakai membandingkannya.
         */
        AnomalyResult: {
            /** Score */
            score: number;
            /** Threshold */
            threshold: number;
            /**
             * Exceeded
             * @description benar bila skor melampaui ambang
             */
            exceeded: boolean;
            /** Heatmap Base64 */
            heatmap_base64?: string | null;
        };
        /**
         * BBox
         * @description Kotak pembatas dalam piksel pada gambar asli.
         */
        BBox: {
            /**
             * X
             * @description tepi kiri
             */
            x: number;
            /**
             * Y
             * @description tepi atas
             */
            y: number;
            /**
             * W
             * @description lebar
             */
            w: number;
            /**
             * H
             * @description tinggi
             */
            h: number;
        };
        /** Body_inspect_image_api_v1_inspect_post */
        Body_inspect_image_api_v1_inspect_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * DecisionDetail
         * @description Angka yang mendasari keputusan, supaya hasilnya dapat ditelusuri.
         */
        DecisionDetail: {
            /** Calibrated Probability */
            calibrated_probability: number;
            /**
             * Prediction Set
             * @description himpunan prediksi conformal; lebih dari satu berarti sistem ragu
             */
            prediction_set: string[];
            /** Severity */
            severity: number;
            /** Conformal Alpha */
            conformal_alpha: number;
        };
        /**
         * Defect
         * @description Satu cacat yang terdeteksi.
         */
        Defect: {
            /**
             * Type
             * @description nama kelas cacat
             */
            type: string;
            /**
             * Label
             * @description nama kelas untuk ditampilkan ke pengguna
             */
            label: string;
            bbox: components["schemas"]["BBox"];
            /** Confidence */
            confidence: number;
            /**
             * Area Pct
             * @description luas cacat terhadap luas gambar, persen
             */
            area_pct?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthStatus
         * @description Kesiapan layanan beserta lapisan model yang aktif.
         *
         *     Endpoint kesehatan sebelumnya mengembalikan `dict` telanjang. Selain
         *     melanggar R3.6, akibatnya lebih praktis: FastAPI tidak dapat menurunkan
         *     skema apa pun untuknya, sehingga endpoint ini tidak muncul di
         *     `/openapi.json` dengan bentuk yang jelas dan Frontend tidak dapat
         *     membangkitkan tipenya - padahal justru endpoint inilah yang dipakai
         *     Frontend memutuskan apakah tombol Periksa layak diaktifkan.
         */
        HealthStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Components
             * @default {}
             */
            components: {
                [key: string]: boolean;
            };
            /** Detail */
            detail?: string | null;
        };
        /**
         * InspectionResult
         * @description Hasil lengkap satu kali inspeksi. Ini yang dikembalikan ke Backend.
         */
        InspectionResult: {
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "PASS" | "REJECT" | "REVIEW";
            /** Reason */
            reason: string;
            /** Confidence */
            confidence?: number | null;
            /** Batch Code */
            batch_code?: string | null;
            /** Defects */
            defects?: components["schemas"]["Defect"][];
            /**
             * Defect Area Pct
             * @default 0
             */
            defect_area_pct: number;
            anomaly?: components["schemas"]["AnomalyResult"] | null;
            decision?: components["schemas"]["DecisionDetail"] | null;
            /**
             * Annotated Image Base64
             * @default
             */
            annotated_image_base64: string;
            /**
             * Model Version
             * @default
             */
            model_version: string;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
        };
        /**
         * ModelInfo
         * @description Keterangan model yang sedang dilayani.
         *
         *     `components` melaporkan lapisan mana yang benar-benar aktif. Sistem tetap
         *     berjalan ketika sebuah model tidak tersedia, dengan kemampuan berkurang,
         *     dan keadaan itu harus dapat dilihat dari luar alih-alih hanya tampak
         *     sebagai hasil yang diam-diam berbeda.
         */
        ModelInfo: {
            /** Model Name */
            model_name: string;
            /** Version */
            version: string;
            /** Dataset */
            dataset: string;
            /** Trained At */
            trained_at?: string | null;
            /**
             * Metrics
             * @default {}
             */
            metrics: {
                [key: string]: number;
            };
            /**
             * Components
             * @default {}
             */
            components: {
                [key: string]: boolean;
            };
        };
        /**
         * SampleImage
         * @description Gambar contoh yang disediakan layanan untuk mencoba sistem.
         */
        SampleImage: {
            /** Name */
            name: string;
            /** Url */
            url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    inspect_image_api_v1_inspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_inspect_image_api_v1_inspect_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_samples_api_v1_samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleImage"][];
                };
            };
        };
    };
    get_model_info_api_v1_model_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfo"];
                };
            };
        };
    };
    health_check_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
